# Generated by Django 3.0.1 on 2019-12-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire_transaction',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='hire_transaction',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
